### ISSUE TITLE
vsc拉取失败

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/llpy-helper-lib#2]
[15:10:39] INFO Repo: https://codeberg.org/moixsuki/HelperLib/raw/branch/master/mirror/
[15:10:40] INFO 开始拉取清单
[15:10:40] INFO 获取到清单内容
[15:10:40] INFO {"name":"Codeberg上的官方镜像补全库","source":"https://github.com/LiteLScript-Dev/HelperLib","wiki":"https://github.com/LiteLDev/LiteLoaderSE-Aids/wiki","library":[{"type":"dts","name":"JS/TS补全库","version":"1.0.2","index":".*/src/index.d.ts","language":"zh-hant","download_url":"https://codeberg.org/moixsuki/HelperLib/archive/master.zip"},{"type":"py","name":"PYTHON补全库","version":"1.0.2","index":"llpy-helper-lib","language":"zh-hant","cmd":"{python} -m pip install llpy-helper-lib -U","tip":"使用pip安装"}]}
[15:10:46] INFO 正在安装库 py
[15:10:46] INFO [PYTHON补全库(zh-hant)] 使用pip安装
[15:10:46] INFO [PYTHON补全库(zh-hant)] 当前Python版本 3.11.5
[15:10:46] INFO [PYTHON补全库(zh-hant)] 正在执行安装命令C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\python.exe -m pip install llpy-helper-lib -U
[15:12:12] ERROR [PYTHON补全库(zh-hant)] 执行安装命令时出现错误 
 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/llpy-helper-lib/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/a1/e7/2735cc28562d3316df5afcc34dcfdcf8944719c66449694467d5c464d483/llpy_helper_lib-2.13.1-py3-none-any.whl
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\http\client.py", line 466, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\ssl.py", line 1311, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 161, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_internal\operations\prepare.py", line 565, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_internal\operations\prepare.py", line 479, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_internal\network\download.py", line 183, in __call__
    for chunk in chunks:
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\yufengya\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by lgc2333** [comment]
网络问题
